const data = [
  {
    id: 1,
    img: "../assets/shoes/shoe-1.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 2,
    img: "../assets/jew/jew-5.png",
    type: "jew",
    name: "مجوهرات",
    price: "25200",
  },
  {
    id: 3,
    img: "../assets/shoes/shoe-2.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 4,
    img: "../assets/jew/jew-1.png",
    type: "jew",
    name: "مجوهرات",
    price: "25200",
  },
  {
    id: 5,
    img: "../assets/shoes/shoe-3.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 6,
    img: "../assets/elct/elct-4.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },
  {
    id: 7,
    img: "../assets/shoes/shoe-4.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },

  {
    id: 8,
    img: "../assets/shoes/shoe-7.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 9,
    img: "../assets/accss/accss-6.png",
    type: "accss",
    name: " اكسسوار",
    price: "500",
  },
  {
    id: 10,
    img: "../assets/shoes/shoe-8.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 11,
    img: "../assets/shoes/shoe-9.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 12,
    img: "../assets/accss/accss-1.png",
    type: "accss",
    name: " اكسسوار",
    price: "500",
  },
  {
    id: 13,
    img: "../assets/accss/accss-2.png",
    type: "accss",
    name: " اكسسوار",
    price: "500",
  },
  {
    id: 14,
    img: "../assets/accss/accss-3.png",
    type: "accss",
    name: " اكسسوار",
    price: "500",
  },
  {
    id: 15,
    img: "../assets/accss/accss-4.png",
    type: "accss",
    name: " اكسسوار",
    price: "500",
  },
  {
    id: 16,
    img: "../assets/accss/accss-5.png",
    type: "accss",
    name: " اكسسوار",
    price: "500",
  },

  {
    id: 17,
    img: "../assets/elct/elct-1.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },
  {
    id: 18,
    img: "../assets/elct/elct-2.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },
  {
    id: 19,
    img: "../assets/elct/elct-3.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },

  {
    id: 20,
    img: "../assets/elct/elct-5.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },
  {
    id: 21,
    img: "../assets/elct/elct-6.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },
  {
    id: 22,
    img: "../assets/elct/elct-7.png",
    type: "elct",
    name: "الكترونيات",
    price: "4200",
  },
  {
    id: 23,
    img: "../assets/shoes/shoe-5.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },

  {
    id: 24,
    img: "../assets/shoes/shoe-6.png",
    type: "shoes",
    name: "جزمة مقاس",
    price: "1200",
  },
  {
    id: 25,
    img: "../assets/furn/furn-1.png",
    type: "furn",
    name: "كرسي او كنبة",
    price: "2200",
  },
  {
    id: 26,
    img: "../assets/furn/furn-1.png",
    type: "furn",
    name: "كرسي او كنبة",
    price: "2200",
  },
  {
    id: 27,
    img: "../assets/furn/furn-1.png",
    type: "furn",
    name: "كرسي او كنبة",
    price: "2200",
  },
  {
    id: 28,
    img: "../assets/furn/furn-1.png",
    type: "furn",
    name: "كرسي او كنبة",
    price: "2200",
  },
  {
    id: 29,
    img: "../assets/furn/furn-1.png",
    type: "furn",
    name: "كرسي او كنبة",
    price: "2200",
  },

  {
    id: 30,
    img: "../assets/jew/jew-2.png",
    type: "jew",
    name: "مجوهرات",
    price: "25200",
  },
  {
    id: 31,
    img: "../assets/jew/jew-3.png",
    type: "jew",
    name: "مجوهرات",
    price: "25200",
  },
  {
    id: 32,
    img: "../assets/jew/jew-4.png",
    type: "jew",
    name: "مجوهرات",
    price: "25200",
  },
];

export default data;
